### 1.Write a Python function create_2d_array() that creates and returns a 2D NumPy array with the following data:

In [1]:
import numpy as np

In [2]:
x=[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
y=np.array([[2,3,4]])
y.shape

(1, 3)

### 2.Write a Python function create_3d_array() that creates and returns a 3D NumPy array with shape     (2, 3, 4) where all the values are initialized to zero.

In [6]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 3. Write a Python function create_1d_array_range() that creates and returns a 1D NumPy array with values from 10 to 20 (inclusive) using np.arange()

In [7]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### 4.Write a Python function create_random_2d_array() that creates and returns a 2D NumPy array with shape (3, 4) where all the values are random numbers between 0 and 10 using np.random.rand()

In [29]:
x=np.random.randint(0,11)
x

2

In [46]:
def create_random_2d_array():
    array = np.random.rand(3,4)
    return array

array = create_random_2d_array()
print(array)

[[0.41522131 0.19175354 0.47366435 0.02047427]
 [0.34674949 0.55723041 0.05593347 0.48945713]
 [0.02038216 0.26506364 0.11085128 0.13078232]]


### 5.Write a Python function create_random_2d_array() that creates and returns a 2D NumPy array with shape (3, 4) where all the values are random numbers between 0 and 10 using np.random.rand()

In [65]:
array = np.random.randint(1, 101, size=(3, 4))
print(array)

[[ 65  98  78  71]
 [ 26  71  58  54]
 [ 85  82 100  13]]


# Accessing the 1D,2D,3D array

### 1. Create a 1D NumPy array of size 6 filled with the number 7. Replace the element at index 4 with the number 12, and print the updated array.

In [100]:
np.random.seed(1)
x=np.random.randint(1,10,size=(3,3))
x[2,1]=6
x

array([[6, 9, 6],
       [1, 1, 2],
       [8, 6, 3]])

### 2. Create a 2D NumPy array of shape (3, 4) with the values from 1 to 12. Access and print the element in the second row and third column.

In [102]:
np.random.seed(1)
x=np.random.randint(1,10,size=(3,4))
x[1,2]

8

### 3.Create a 2D NumPy array with the values [[10, 20, 30], [40, 50, 60], [70, 80, 90]]. Use slicing to extract and print the second row and all columns.

In [106]:
arr2=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr2[:2,:]

array([[10, 20, 30],
       [40, 50, 60]])

### 4. Create a 2D NumPy array of shape (4, 3) filled with random integers between 1 and 100. Use slicing to extract the last two rows and the first two columns.

In [111]:
np.random.seed(1)
x=np.random.randint(1,10,size=(4,3))
x[-2:,0:2]

array([[8, 7],
       [5, 6]])